Availity/availity-angular

- lib/core/session/session.js
- lib/core/session/tests/session-spec.js
Added a new hasPermission method to avSession which checks whether a given permission (optionally within an org and/or region) is present
> Added a new hasPermission method to avSession

- gulp/config.js
- lib/ui/popover/docs/popover-ui-demo.html
- lib/ui/popover/docs/popover-ui-demo.js
- lib/ui/popover/popover.js
> Basic support for Bootstrap Popovers

- lib/core/api/tests/api-factory-spec.js
- lib/ui/validation/adapter-bootstrap.js
- lib/ui/validation/docs/validation-ui-demo.html
- lib/ui/validation/messages.js
- lib/ui/validation/tests/adapter-bootstrap-spec.js
- lib/ui/validation/tests/field-spec.js
- lib/ui/validation/tests/form-spec.js
* support error message containers from anywhere in the dom
> Dynamic error containers

- lib/ui/validation/field.js
- lib/ui/validation/tests/field-spec.js
* validation framework should prevent the Angular model from updating with invalid data
> validation framework parser fix

- lib/core/api/api-factory.js
- lib/core/polling/polling.js
- lib/core/polling/tests/polling-spec.js
> add headers to polling service request

- lib/ui/placeholder/placeholder.js
addressing this issue https://github.com/Availity/availity-angular/issues/87
> placeholder switches core to ui

- lib/core/api/api-factory.js
- lib/core/api/api-organizations.js
- lib/core/api/tests/api-organizations-spec.js
To allow params to be sent into the organizations
> allows params to be sent for organizations

- lib/core/api/api-factory.js
- lib/core/api/tests/api-factory-spec.js
- package.json
The code was clobbering the config parameter before using it.
> Fixed update-without-id bug with the config parameter

- docs/guide/js/index.js
- docs/guide/templates/partials/default-footer.hbs
- lib/ui/mask/docs/mask-ui-demo.html
> fixed docs to show examples again

- bower.json
- gulp/config.js
- lib/core/api/tests/api-factory-spec.js
- lib/ui/removable-label/docs/removable-label-ui-demo.html
- lib/ui/removable-label/docs/removable-label-ui-demo.js
- lib/ui/removable-label/removable-label-tpl.html
- lib/ui/removable-label/removable-label.js
- lib/ui/removable-label/tests/removable-label-spec.js
directive wrapping [availity-uikit's removable label styles](http://availity.github.io/availity-uikit/components.html#RemovableLabels)
> adding removable labels

- lib/ui/breadcrumbs/breadcrumbs.js
- lib/ui/breadcrumbs/tests/breadcrumbs-spec.js
> breadcrumbs replace the element they are placed on

- lib/ui/modal/docs/modal-lg-template.html
- lib/ui/modal/docs/modal-sm-template.html
- lib/ui/modal/docs/modal-ui-demo.html
- lib/ui/modal/docs/modal-ui-demo.js
- lib/ui/modal/modal-tpl.html
- lib/ui/modal/modal.js
Like Bootstrap's: http://getbootstrap.com/javascript/#modals-sizes
Large
Small
> allow modals to have different sizes

- docs/guide/js/index.js
- gulp/config.js
- lib/ui/tabs/docs/tabs-ui-demo.html
- lib/ui/tabs/tab-tpl.html
- lib/ui/tabs/tabs-tpl.html
- lib/ui/tabs/tabs.js
- lib/ui/tabs/tests/tabs-spec.js
- test/matchers.js
> Bootstrap Tab Directives

- lib/ui/modal/modal.js
- lib/ui/modal/tests/modal-fixture.html
- lib/ui/modal/tests/modal-spec.js
* closes #155
* fixes modal.hide(), modal.toggle() and modal.show() promise resultion
> modal promises not resolving

- gulp/config.js
- lib/core/validation/validators/tests/validator-date-format-spec.js
- lib/core/validation/validators/tests/validator-npi-spec.js
- lib/core/validation/validators/validator-npi.js
> Add NPI Validator

- lib/core/analytics/docs/analytics-core-demo.html
- lib/ui/analytics/analytics.js
- lib/ui/analytics/tests/analytics-fixture.html
- lib/ui/analytics/tests/analytics-spec.js
- package.json
Fix for Issue #176 , may need another test case, unsure of that.
> Added category directive and added category attribute to test case

- lib/ui/dropdown/dropdown.js
closeOnResize can be set but the dropdown will still automatically close regardless of value set
> adding check for closeOnResize value

- lib/ui/dropdown/dropdown.js
- lib/ui/dropdown/tests/dropdown-spec.js
Noticed an issue trying to create a simple Yes/No type of dropdown.  If the value of the model was false, it wouldn't select an option because we were using a simply truthy evaluation of the viewValue.
> Dropdown not defaulting when ngModel set to false

- lib/core/analytics/docs/analytics-core-demo.html
Updated the docs per Kasey Powers request
> Updated docs regarding analytics

- gulp/config.js
- lib/ui/modal/docs/modal-template.html
- lib/ui/tooltip/docs/tooltip-ui-demo.html
- lib/ui/tooltip/docs/tooltip-ui-demo.js
- lib/ui/tooltip/tests/show-fixture.html
- lib/ui/tooltip/tests/tooltip-spec.js
- lib/ui/tooltip/tooltip.js
- lib/ui/validation/docs/validation-ui-demo.html
Add tooltip to wrap bs.tooltip similar to popover
Add tooltip docs/exmaples
Fix tooltip in modal exmaple
> feat(tooltip): add avTooltip directive

- lib/ui/modal/docs/modal-template.html
- lib/ui/popover/docs/popover-ui-demo.html
Remove data-toggle attr, av doesn't use it
Fix Show popover on load, it now shows on load
Add av attr to popover in modal to demo popover in modal
> docs(popover): cleanup popover in docs

- lib/ui/breadcrumbs/breadcrumbs.js
- lib/ui/breadcrumbs/tests/breadcrumbs-spec.js
Added ability for breadcrumbs to specify a level (rather than an explicit parent) to make dynamic, context-sensitive breadcrumbs.
> Added dynamic breadcrumbs

- src/ui/dropdown/docs/dropdown.html
- src/ui/dropdown/docs/fixtures/photos-1.json
- src/ui/dropdown/docs/fixtures/photos-2.json
- src/ui/dropdown/docs/picturesResultFormat.js
- src/ui/dropdown/docs/service.js
> Added an example to show html usage in dropdown

- lib/core/api/api-spaces.js
- lib/ui/breadcrumbs/breadcrumbs-spaces-tpl.html
- lib/ui/breadcrumbs/breadcrumbs-spaces.js
> fixed issue with breadcrumbs

- lib/ui/validation/form.js
- lib/ui/validation/tests/form-spec.js
Removed from the previous PR due to me attempting to solve two problems at once. Re-adding as it seems to be working.
> re-adding the evaluate

- less/availity-scaffolding.less
Fixes styling of disabled elements with angular click events.
> AZ-833 - fixed [ng-click][disabled] hover and focus styling

- src/ui/modal/directive.js
- src/ui/validation/container.js
Resolving issue #142, 
Adding element option to directives where it makes sense.
> Updating directive restrictors

- src/ui/validation/container.js
Not too sure why this was in there, but it shouldn't been needed and GF asked for it to be removed.
> Remove $sce

- src/ui/validation/container.js
- src/ui/validation/field.js
- webpack.config.production.js
Removing unused $timeout in field.js, possibly un-needed digest triggers in test
> Fixing Tests

- src/core/analytics/exceptions.js
If no stack is on the stack trace, try to make one before giving up.
Closes #280
> fix(avExceptionAnalytics): handle no stack

- src/ui/dropdown/controller.js
This was further change on same previous issue.  The problem I was seeing that when page loads depending on on av-dropdown is loaded is string value and not modelValue.   Best to use modelValue when using query.
> issue #286 found another issue with query option not representing model.

- src/ui/dropdown/directive.js
- src/ui/uploads/tests/upload-progress-bar-spec.js
https://github.com/Availity/availity-angular/issues/295
IE  does not recognize `includes` method
> change includes method to indexOf

- package.json
- src/ui/uploads/upload-progress-bar.html
- src/ui/uploads/upload-progress-bar.js
Focus on the input field in the popup and make the 'enter' button submit the input like manually clicking the 'ok' button does
> fix(uploads): password prompt enter and focus

- lib/core/api/api-factory.js
- lib/core/api/tests/api-factory-spec.js
- package.json
This back ports the feature from v2
> feat(api-factory): add all method to get all the data from all of the pages
