lib/core/validation/validators/validator-date-range-spec.js, lib/core/validation/validators/validator-date-range.js
This is adding a format check to the dateRange validator. I ran into an issue where I had MM/DD/YYYY as my format in dateRange however a date such as 13/01/2014 was valid and converted to 01/01/2015 when validating. This also happened for days such as 06/33/2015 would validate as 07/02/2015.
=> bugfix: Adding format valid check to date range

lib/ui/breadcrumbs/breadcrumbs.js, lib/ui/breadcrumbs/tests/breadcrumbs-spec.js
Breadcrumbs weren't being set until a $stateChangeSuccess occurred. Now they are set initially then updated when $stateChangeSuccess occurs.
=> breadcrumbs are now initializing

gulp/config.js, lib/ui/badge/badge-tpl.html, lib/ui/badge/badge.js, lib/ui/badge/docs/badge-ui-demo.html, lib/ui/badge/tests/badge-spec.js, lib/ui/filters/approximate.js, lib/ui/filters/docs/filters-ui-demo.html, lib/ui/filters/docs/filters-ui-demo.js, lib/ui/filters/tests/approximate-spec.js, package.json
The approximate filter will format numbers in a friendly manner e.g. 1,000 -> 1k, 1,000,000 -> 1M, etc.
The badge directive wraps the existing badge styles and applies the approximate filter to the badge count. Badges typically don't look great with large counts.
=> add badge directive and approximate filter

lib/core/api/api-codes.js, lib/ui/dropdown/docs/dropdown-ui-demo.js, lib/ui/dropdown/dropdown.js, lib/ui/dropdown/tests/dropdown-spec.js
dropdown multiselect required indices to set the initial state. This allows your ng-model to be an array of objects and it will select those indices in your ng-options and send it to select2 to display.
This change won't run if you have an array of integers. So the original way of setting multiselect still works.
=> Multivalue object dropdown fix

lib/core/logger/logger.js
There may be a more appropriate place for this code (perhaps in the error method, since I don't think we would have stack traces in any other method call), but this fix worked for me locally. Debugging is now possible!
=> Add check for stack in logger so that it is included in error messages

lib/ui/datepicker/datepicker.js, lib/ui/datepicker/tests/datepicker-spec.js, package.json
The existing code causes an issue in the scenario where the model is set prior to initialization (i.e. editing an existing date). The old code used formatters to change the model value. However, this in turn would cause the watcher in angular to trigger, and the formatters would once again kick in, as to them it looks like there was a model change. This continues indefinitely.
There really isn't a need to change the model value. Rather, we just let the formatter chain to do the work for us. In other words, let one formatter pass along the object needed by the next.
=> Fixes for datepicker formatters

lib/ui/modal/modal.js
Allow the completion of the asynchronous events to be determined by actually returning the promise.
=> Return the promise from modal scope calls.

lib/core/api/api-factory.js, lib/core/api/tests/api-factory-spec.js
This allows `AvApiResource` to intelligently build ulrs by joining option path segments properly even when the segements are misssing the slash `\` character
=> Enhance api resource URL building

lib/ui/modal/docs/modal-ui-demo.html, lib/ui/modal/docs/modal-ui-demo.js, lib/ui/modal/docs/modal-with-controller-template.html, lib/ui/modal/modal.js, lib/ui/modal/tests/modal-spec.js
Support for `controller` and `controllerAs` properties on the AvModal config object, that behave the same as on a route or a directive.  
You can pass a function or a name of a controller registered with `angular.module().controller()`.  Specifying `controllerAs` will attach the controller to the scope with the given name.
There is also a `locals` option, which specifies values that can be injected into that specific instance of the controller (`$scope` is included by default, as is done in routes and directives).  This is a less common, but very standard feature of angular.
=> Added ability for AvModal to be created specifying a controller rather than a scope

lib/core/logger/logger.js, lib/core/logger/tests/logger-spec.js
Fixed bug in supplant where it would incorrectly interpret {} in angular error messages as an attempt to supplant undefined data.
I ended up going with the simple null check in the supplant function.  It's a good safe way to correctly handle null supplantData in any scenario that calls supplant.  While I feel that in this particular scenario, we shouldn't even be attempting to supplant, this fixes the problem, and is an overall improvement to the method.
Looking over the logic that chose to call supplant in the first place, I'm not entirely certain that it is correctly in alignment with the API of `$log`, and might run into further issues in other edge cases.  Such as if an error comes in with a stack, but as only one arg, or if a 'cause' is supplied as the second parameter to …
=> Fix for issue #175, where supplant was messing up angular error messages

lib/core/validation/validator.js, lib/ui/validation/field.js
Fix invalid error messages displaying in console when the form validation key has not resolved.  This issue can happen when the form validation key is resolved inside a promise.  Fixes #237
=> Fix invalid error messges on page load for form validation

lib/ui/validation/adapter-bootstrap.js
This is to fix the issue when an error message "top" was displaying. The last fix needed a validation to check if the offset is returning anything so the top would returned.
=> added null check to avoid exception when element is hidden

lib/core/analytics/analytics-exceptions.js, lib/core/analytics/tests/analytics-exceptions-spec.js
There isn't much value in logging hundreds or thousands of duplicate errors. This will prevent a given error from being logged too frequently.
=> Add error log limiter to prevent slamming the API with duplicate errors

lib/ui/validation/field.js, lib/ui/validation/form.js, lib/ui/validation/tests/field-spec.js, lib/ui/validation/tests/form-spec.js
Allows fields to inherit av-val-show from the form. similar to how av-val-on works. 
Also, it can also be a variable on the form where av-val-show on fields seems to always fire if the attribute exists.
=> allows fields to get av-val-show from the form

lib/ui/validation/adapter-bootstrap.js, lib/ui/validation/adapter.js, lib/ui/validation/field.js, lib/ui/validation/form.js, lib/ui/validation/tests/form-spec.js
removes processing of av-val-show because its slow and immediate validation should be asap. provides a way for container-id to work with variables such as an $index
=> Fixes for avValShow and av-val-container with custom ids

src/core/api/README.md, src/core/api/resource.js, src/core/api/tests/resource-spec.js
For issue #256 
Recognizing the need to make GET requests with hidden info in the body of the message.
=> Adding postGet function to send data with X-HTTP-Method-Override header set to GET

src/core/api/regions.js
the regions api now allows for a currentlySelected parameter, changing the getCurrentRegion function to use this parameter. This will be the only region needed for most cases, so we reduce the payload size as well as prevent an issue with users having more than 50 regions available. 
Updated the getRegions function to only add the userId if one is not already in the config.
=> Updating regions resource for api change, updating the getRegions function

src/ui/dropdown/controller.js
closes #193
When element is type select, initSelection is provided by select2, otherwise default it to an empty function.
=> Adding default initSelection when needed

src/ui/ui.less
Fixes text color of disabled buttons with ng-click
=> Allow bootstrap to set disabled button text color

src/ui/dropdown/controller.js
We don't want to call the "uuid" function within the parenthesis. Otherwise, if nextUidFn is undefined, we will call the result of uuid() (which is a string) as a function.
=> Remove premature call to function

src/ui/dropdown/controller.js
The 'select as' syntax will have the model as a property of the collection items and not the item itself. We need to check if the item matches using the key
=> fix(Dropdown): account for 'select as'

lib/core/analytics/analytics-exceptions.js
Backport to v1:
If no stack is on the stack trace, try to make one before giving up.
Closes #280
=> fix(avExceptionAnalytics): handle no stack (v1)

src/ui/dropdown/resource.js
when no results are returned from a service call, a console error is thrown
=> additional check when getting results

src/core/api/resource.js
Previous getPost was checking if `this.beforeCreate` existed before calling `this.beforePostGet`
this corrects this by checking for `this.beforePostGet` before calling `this.beforePostGet`.
=> fix(resource): fix incorrect variable check

src/ui/uploads/upload-progress-bar.js
allows users to add an attribute to the progress bar:
`<av-upload-progress-bar upload="upload" callback="request.onErrorCallback"></av-upload-progress-bar>`
that will be called when/if an error occurs to change the errorMessage
```
onErrorCallback(upload) {
upload.errorMessage = 'custom error message';
}
```
=> fix(upload-core): add errorCallback

src/ui/breadcrumbs/spaces.html, src/ui/breadcrumbs/spaces.js, src/ui/breadcrumbs/tests/spaces-spec.js
Useful if you want to use spaces breadcrumbs directive for spaces that are not of type "space"
=> feat(breadcrumbs): add option to use url from space

src/ui/uploads/template-password-prompt.html
buttons with no type or a type of submit only are valid within a form. The password request for uploads has a button with type="submit" which is not within a form, this causes issues when the modal itself does appears within a form. Clicking the button will submit the parent form, which is not the password prompt form.
=> fix(uploads): change button to type of button
